project_name              = "teedy"
do_token                  = ""
region                    = "fra1"
size                      = "s-1vcpu-1gb"
desktop_public_ssh_key    = "~/.ssh/id_rsa.pub"
terraform_public_ssh_key  = "ssh.pub"
terraform_private_ssh_key = "ssh"
domain                    = ""
