project_name           = "teedy"
do_token               = ""
region                 = "fra1"
desktop_public_ssh_key        = "~/.ssh/id_rsa.pub"
terraform_public_ssh_key        = "ssh.pub"
terraform_private_ssh_key        = "ssh"
